[package]
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"
name = "gravity_utils"
version = "0.1.0"

[dependencies]
gravity_proto = { path = "../gravity_proto/" }

clarity = "0.5"
deep_space = "2.8"
log = "0.4"
num-bigint = "0.4"
num256 = "0.3"
serde = "1.0"
serde_derive = "1.0"
sha3 = "0.10"
tokio = "1.4"
tonic = "0.6"
url = "2"
web30 = { git = "https://github.com/onomyprotocol/web30.git", rev = "0f96ccd53867bafe4c08ae59a1266ec0256e1cd4" }

[dev_dependencies]
rand = "0.8"
