[package]
name = "gravity_proto"
version = "0.1.0"
authors = ["Justin Kilpatrick <justin@althea.net>"]
edition = "2018"

[dependencies]
cosmos-sdk-proto = { package = "cosmos-sdk-proto-althea", version = "0.13" }
prost = "0.10"
prost-types = "0.10"
tonic = "0.7"
